# Generated by Django 2.2 on 2023-03-17 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='doctorId',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='hospital.DoctorModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='endTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='status',
            field=models.CharField(default='Attending', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='symtopms',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='userId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient.PatientModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='startTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
