# Generated by Django 2.2 on 2023-03-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20230317_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='doctorId',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='userId',
        ),
    ]
