# Generated by Django 2.2 on 2023-03-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20230317_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='docterId',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='userId',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
