# Generated by Django 2.2 on 2023-03-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctormodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='occupiedBy',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
