# Generated by Django 2.2 on 2023-03-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_doctormodel_occupiedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='roomNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
