# Generated by Django 2.2 on 2023-03-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_doctormodel_roomnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='roomNumber',
            field=models.IntegerField(default=0),
        ),
    ]
