# Generated by Django 2.2 on 2023-03-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceDetection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=10)),
                ('bloodGroup', models.CharField(max_length=20)),
            ],
        ),
    ]
